### ISSUE TITLE
Does not work with version ^1.18

### ISSUE THREAD

**Issue by rymndhng** [rybakit/twig-extensions-deferred#3]
This is somewhat strange.

When I run the tests in your project, it seems to work fine against `1.18.2`. However, in my own project when I try to use `1.18.2`, the deferred blocks render nothing. When I use twig `1.17.0`, everything works as expected.

I tried to render the demos on `README` to no avail.

**Comment by rymndhng** [comment]
Derp, I see the problem. The issue is that I was using `0.2.0` when I need `dev-master#e699a1f`. Is there any plans to slate a new release?

**Comment by rybakit** [comment]
[Done](https://github.com/rybakit/twig-extensions-deferred/tree/v0.3.0).

**Comment by rymndhng** [comment]
:+1: thanks!
